### PR TITLE
Getting ready for release

### PR DESCRIPTION
**Pull request by Westlanderz**
With this PR the first version of the game will be released.

### CODE REVIEW

**Comment by Dennisbonke** [comment]
I presume we hold this until tomorrows work day is done?

**Comment by Westlanderz** [comment]
> I presume we hold this until tomorrows work day is done?

Yes thats why it is a draft

**Review by Dennisbonke — APPROVED** [review]
LGTM

**Review by Duma0 — APPROVED** [review]
LGTM

**Pull request merged**
