### PR TITLE
Finishing off the 0.6 development cycle

### PR DESCRIPTION
**Pull request by Dennisbonke**
This finalizes the 0.6 'Electra' development cycle.

### CODE REVIEW

**Review by drfdaniel — DISMISSED** [review]
LGTM

**Review by Westlanderz — CHANGES_REQUESTED** [review]
The changes are good, but as I have said earlier once the leveltransitions get merged you have to revert the sprite of the ending button for the pixel perfect state. So you should change that before merging.

**Comment by Dennisbonke** [comment]
> The changes are good, but as I have said earlier once the leveltransitions get merged you have to revert the sprite of the ending button for the pixel perfect state. So you should change that before merging.

Which file exactly are you talking about?

**Review by drfdaniel — APPROVED** [review]
LGTM

**Comment by Westlanderz** [comment]
The last commit message is not consistent with the rest, you use `ui` (lowercase) instead of `UI` (uppercase) this should be made consistent with the rest.

**Review by Westlanderz — APPROVED** [review]
As you have changed the file, this all looks good now.

**Pull request merged**
