### PR TITLE
Singletons

### PR DESCRIPTION
**Pull request by Westlanderz**
This PR adds a simple way forward to declare singleton classes through inheritance. All classes that were already singletons are refactored to this new way. This PR also solves tight coupling between the core layer and others, this is now solved through events and components outside the core layer that had base abstract forms in the core layer do not need those anymore. Due to possible conflits with other PRs merge this one after #117, #118, #119 and #120 are merged.

### CODE REVIEW

**Review by drfdaniel — APPROVED** [review]
LGTM

**Review by Dennisbonke — APPROVED** [review]
LGTM but holding as requested

**Review by drfdaniel — APPROVED** [review]
LGTM

**Review by Dennisbonke — APPROVED** [review]
LGTM now

**Pull request merged**
