### PR TITLE
Tutorial V2

### PR DESCRIPTION
**Pull request by drfdaniel**
Reworked tutorial level based on new shape. New texture locations and prefab locations. 

OPA-344

### CODE REVIEW

**Review by Westlanderz — CHANGES_REQUESTED** [review]
First of all the commit history is not linear so we cannot approve this. And second the checks fail and I'd like that to be fixed as well.

**Comment by Dennisbonke** [comment]
I'll try to fix the conflicts and merge commits, the ci failure seems to be spurious, and no logs are found. We'll rerun the jobs when I've fixed this stuff.

**Comment by Dennisbonke** [comment]
> I'll try to fix the conflicts and merge commits, the ci failure seems to be spurious, and no logs are found. We'll rerun the jobs when I've fixed this stuff.

For some reason, massive performance regressions were found with this PR. Needs more investigating at a later date.

**Review by Dennisbonke — CHANGES_REQUESTED** [review]
This PR introduces some unexplainable performance losses. After careful consideration and discussion, the best course of action is probably starting from scratch. We think the issue is in the scene itself, so you can keep the json file, but that too will need some changes. See me at a moment where we don't have the prefab performance issues, so I can show you what issues remain in that department. For now, this can not be merged, or even attempted to be fixed up, and as such this PR will remain in the current state.

**Pull request closed without merging**
